export const courses = [
    {
        title: 'How to Groom a Goldendoodle',
        subtitle: '(and Other Curly Coats)',
        description: "If your dog has a lush, curly coat, this course is for you! Learn to properly brush out tangles, shape the perfect teddy bear trim, and maintain a healthy curl. You'll master every step of the grooming for a happy, well-groomed pooch.",
        highlights: ['Step-by-step detangling methods', 'Professional trimming tips', 'Product recommendations for curly coats'],
        greatFor: 'Poodles, Goldendoodles, Labradoodles, Bichons, and other curly-coated breeds',
        imageSrc: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2159797494/settings_images/70a8dad-ed23-45b-8e1-d08da826a6_doodle-thumb-edit.jpg',
        learnHref: '/courses/how-to-groom-a-goldendoodle',
        enrollHref: '/resource_redirect/offers/ypsFd4NT',
        price: '$248',
    },
    {
        title: 'Teddy Bear Cuts',
        subtitle: '(for Small Plush Dogs)',
        description: "Give your pup an adorable, plush teddy bear cut from the comfort of home. This  course will guide you through every step of grooming your fluffly friend, from detangling that cloud-like coat to shaping the perfect teddy bear cut.",
        highlights: ['Scissoring techniques for small frames', 'Pro tips to enhance the coat', 'Coat-specific product recommendations'],
        greatFor: 'Shih Tzus, Havanese, Pomeranians, Lhaso Apsos and mixed fluffy breeds',
        imageSrc: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2159797494/settings_images/0e750d-3400-b773-7e50-b80e074f1e8e_teddy-bear--thumb.jpg',
        learnHref: '/courses/teddy-bear-cuts',
        enrollHref: '/resource_redirect/offers/A9oi3pRZ',
        price: '$248',
    },
    {
        title: 'How to Groom a Yorkie',
        subtitle: '(and Other Silky Coats)',
        description: "Master expert grooming techniques to keep silky coats tangle-free and perfectly styled.",
        highlights: ['Brushing and detangling techniques', 'Bathing and drying', 'Pro tips for trims'],
        greatFor: 'Yorkies, Maltese, Morkies and other small, silky mixes',
        imageSrc: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2159797494/settings_images/14bd126-a2b4-33f8-6820-4e57c3b44502_yorkie-2-thumb-no-bg.jpg',
        learnHref: '/courses/how-to-groom-a-yorkie',
        enrollHref: '/resource_redirect/offers/M8B9bLhc',
        price: '$248',
    },
    {
        title: 'How to Groom a Terrier',
        subtitle: '(for Border Terriers and Cairn Terriers)',
        description: "Wire-coated breeds need special care. Learn hand-stripping and carding to keep coats healthy without damage.",
        highlights: ['Hand-stripping basics', 'Maintaining wiry texture', 'Avoiding skin irritation'],
        greatFor: 'Border Terriers, Cairn Terriers other wire-coated mixes',
        imageSrc: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2159797494/settings_images/63fbf3-700b-251-86a1-dbd5876ef316_terrier-thumb-no-bg.jpg',
        learnHref: '/courses/how-to-groom-a-terrier',
        enrollHref: '/resource_redirect/offers/fZttPBGB',
        price: '$248',
    },
    {
        title: 'How to Groom a Golden Retriever',
        subtitle: '(and Other Double Coats)',
        description: "Comprehensive home-grooming course to manage shedding and matting for double-coated breeds.",
        highlights: ['Removing loose undercoat', 'Seasonal shedding cycles', 'Top tools for thick coats'],
        greatFor: 'Golden Retrievers, Huskies, German Shepherds, Collies, and other double-coated dogs',
        imageSrc: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2159797494/settings_images/1cc03a4-be55-140b-63e6-582ac6be248d_golden-thumb-no-bg.jpg',
        learnHref: '/courses/how-to-groom-a-golden-retriever',
        enrollHref: '/resource_redirect/offers/W4jL2sL9',
        price: '$248',
    },
    {
        title: 'How to Groom a Pug',
        subtitle: '(and Other Short Coats)',
        description: "Short coats still benefit from proper grooming: wrinkle care, bathing, and shedding control.",
        highlights: ['Wrinkle care and cleaning', 'Bathing for sensitive skin', 'Minimizing shedding'],
        greatFor: 'Pugs, French Bulldogs, Boxers, Beagles — any short-coated breeds',
        imageSrc: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2159797494/settings_images/40b1f76-d8bb-b6ab-45-aaee4327876d_pug-thumb-no-bg.jpg',
        learnHref: '/courses/how-to-groom-a-pug',
        enrollHref: '/resource_redirect/offers/6Fzcenzo',
        price: '$248',
    },
];
